### ISSUE TITLE
Incorrect casting on `max*` functions.

### ISSUE THREAD

**Issue by alcueca** [yieldprotocol/yieldspace-tv#76]
[Here](https://github.com/yieldprotocol/yieldspace-tv/blob/fc7d8a387761f3f432a569bd56712cc3f91d73cd/src/YieldMath.sol#L575)
`(fyTokenOut = fyTokenReserves - uint128(rightTerm.mulu(WAD))) <= MAX`

`fyTokenReserves` is an uint128, and so is `uint128(rightTerm.mulu(WAD))`. Their substraction can underflow and remain under MAX. Either cast both to uint256, do a comparison between them, or verify that `fyTokenOut < fyTokenReserves` after the substraction.

Similar error [here](https://github.com/yieldprotocol/yieldspace-tv/blob/fc7d8a387761f3f432a569bd56712cc3f91d73cd/src/YieldMath.sol#L629).

**Comment by Sabnock01** [comment]
Resolved by #78
